{{- include "validate.singleEnabledDatabase" . -}}
{{- range $name, $db := .Values.lensesHq.storage }}
{{- if $db.enabled }}
{{- if contains "createNew" $db.passwordSecret.type }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "databaseSecretName" $ }}
  labels:
    app: {{ include "fullname" $ | quote }}
    chart: {{ printf "%s-%s" $.Chart.Name $.Chart.Version }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    component: "lenses-hq"
    lenses.io/app: {{ include "fullname" $ }}
    lenses.io/app.type: lenses-hq-db-secret
type: Opaque
data:
  password: {{ $db.passwordSecret.password | b64enc }}
{{- end }}
{{- end }}
{{- end }}