apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . | quote }}
  labels:
    app: {{ include "fullname" . | quote }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: "lenses-hq"
    lenses.io/app: {{ include "fullname" . }}
    lenses.io/app.type: lenses-hq
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "fullname" . | quote }}
  strategy:
    type: {{ default "Recreate" .Values.strategy.type | quote }}
  template:
    metadata:
      labels:
        app: {{ include "fullname" . | quote }}
        component: "lenses-hq"
        hostPort: {{ .Values.restPort | quote }}
        containerPort: {{ .Values.restPort | quote }}
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      annotations:
        {{- range $key, $value := .Values.podTemplateAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml .Values.dnsConfig | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "fullname" . | quote}}
            items:
              - key: config.toml
                path: config.toml
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets: {{ .Values.image.imagePullSecrets | toYaml | nindent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["/etc/panoptes/config.toml"]
        {{- if .Values.containerSecurityContext}}
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        {{- end }}
        ports:
          - containerPort: {{ .Values.restPort }}
            name: {{ .Values.servicePortName }}
            protocol: TCP
          - containerPort: 10000
            name: agents
            protocol: TCP
          - containerPort: {{ .Values.lensesHq.monitoring.port }}
            name: metrics
            protocol: TCP
        {{- if .Values.lensesHq.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.restPort }}
          {{- if .Values.lensesHq.tls.enabled }}
            scheme: HTTPS
          {{- end }}
          initialDelaySeconds: 300
          periodSeconds: 10
        {{- end }}
        volumeMounts:
          - name: config
            mountPath: /etc/panoptes
          {{- if .Values.additionalVolumeMounts }}
            {{- toYaml .Values.additionalVolumeMounts | nindent 10 }}
          {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
          {{- if .Values.lensesHq.pauseExec.enabled }}
          - name: PAUSE_EXEC
            value: "false"
          {{- end }}
          - name: LENSESHQ_PG_PASSWORD
            valueFrom:
              secretKeyRef:
              {{- if contains "createNew" .Values.lensesHq.postgres.passwordSecret.type }}
                name: {{ include "databaseSecretName" . }}
                key: "password"
              {{ else if or (contains "precreated" .Values.lensesHq.postgres.passwordSecret.type) (contains "externalSecret" .Values.lensesHq.postgres.passwordSecret.type) }}
                name: {{ .Values.lensesHq.postgres.passwordSecret.name }}
                key: {{ .Values.lensesHq.postgres.passwordSecret.key }}
                
              {{- end }}
