apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . | quote }}
  labels:
    app: {{ include "fullname" . | quote }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: "lenses-hq"
    lenses.io/app: {{ include "fullname" . }}
    lenses.io/app.type: lenses-hq
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "fullname" . | quote }}
  strategy:
    type: {{ default "Recreate" .Values.strategy.type | quote }}
  template:
    metadata:
      labels:
        app: {{ include "fullname" . | quote }}
        component: "lenses-hq"
        hostPort: {{ include "extractPort" .Values.lensesHq.http.address | quote }}
        containerPort: {{ include "extractPort" .Values.lensesHq.http.address | quote }}
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      annotations:
        checksum/config: {{ include "lensesHqConfigmap" . | sha256sum }}
        {{- range $key, $value := .Values.podTemplateAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml .Values.dnsConfig | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "fullname" . | quote}}
            items:
              - key: config.yaml
                path: config.yaml
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets: {{ .Values.image.imagePullSecrets | toYaml | nindent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["/etc/panoptes/config.yaml"]
        {{- if .Values.containerSecurityContext}}
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        {{- end }}
        ports:
          - containerPort: {{ include "extractPort" .Values.lensesHq.http.address }}
            name: {{ .Values.servicePortName }}
            protocol: TCP
          - containerPort: {{ include "extractPort" .Values.lensesHq.agents.address }}
            name: agents
            protocol: TCP
          - containerPort: {{ include "extractPort" .Values.lensesHq.metrics.prometheusAddress }}
            name: metrics
            protocol: TCP
        {{- if .Values.lensesHq.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ include "extractPort" .Values.lensesHq.http.address }}
          {{- if .Values.lensesHq.livenessProbe.tls.enabled }}
            scheme: HTTPS
          {{- end }}
          initialDelaySeconds: 300
          periodSeconds: 10
        {{- end }}
        volumeMounts:
          - name: config
            mountPath: /etc/panoptes
          {{- if .Values.additionalVolumeMounts }}
            {{- toYaml .Values.additionalVolumeMounts | nindent 10 }}
          {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
          {{- if (.Values.lensesHq.agents.tls).enabled }}
          - name: LENSESHQ_AGENTS_TLS_KEY
            valueFrom:
              secretKeyRef:
                name: {{.Values.lensesHq.agents.tls.privateKey.secret.name }}
                key: {{ .Values.lensesHq.agents.tls.privateKey.secret.key }}
          {{- if (.Values.lensesHq.agents.tls.cert).referenceFromSecret }}
          - name: LENSESHQ_AGENTS_TLS_CERT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.lensesHq.agents.tls.cert.secretName }}
                key: {{ .Values.lensesHq.agents.tls.cert.secretKeyName }}
          {{- end }}
          {{- end }}
          {{- if (.Values.lensesHq.http.tls).enabled }}
          - name: LENSESHQ_HTTP_TLS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.lensesHq.http.tls.privateKey.secret.name }}
                key: {{ .Values.lensesHq.http.tls.privateKey.secret.key }}
          {{- if (.Values.lensesHq.http.tls.cert).referenceFromSecret }}
          - name: LENSESHQ_HTTP_TLS_CERT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.lensesHq.http.tls.cert.secretName }}
                key: {{ .Values.lensesHq.http.tls.cert.secretKeyName }}
          {{- end }}
          {{- end }}
          {{ if and ((.Values.lensesHq.auth.saml.authnRequestSignature).enabled) }}
          {{ if (not (empty .Values.lensesHq.auth.saml.authnRequestSignature.authnRequestSigningKey.secret.name)) }}
          - name: LENSESHQ_AUTH_SAML_SIGNREQ_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.lensesHq.auth.saml.authnRequestSignature.authnRequestSigningKey.secret.name }}
                key: {{ .Values.lensesHq.auth.saml.authnRequestSignature.authnRequestSigningKey.secret.key }}
          {{- end }}
          {{- if  (.Values.lensesHq.auth.saml.authnRequestSignature).authnRequestSigningCert.referenceFromSecret }}
          - name: LENSESHQ_AUTH_SAML_SIGNREQ_CERT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.lensesHq.auth.saml.authnRequestSignature.authnRequestSigningCert.secretName }}
                key: {{ .Values.lensesHq.auth.saml.authnRequestSignature.authnRequestSigningCert.secretKeyName }}
          {{- end }}
          {{- end }}
          {{- if and .Values.lensesHq.auth.saml.enabled .Values.lensesHq.auth.saml.metadata.referenceFromSecret }}
          - name: LENSESHQ_AUTH_SAML_METADATA
            valueFrom:
              secretKeyRef:
                name: {{ .Values.lensesHq.auth.saml.metadata.secretName }}
                key: {{ .Values.lensesHq.auth.saml.metadata.secretKeyName }}
          {{- end }}
          {{- if .Values.lensesHq.license.referenceFromSecret }}
          - name: LENSESHQ_LICENSE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.lensesHq.license.secretName }}
                key: {{ .Values.lensesHq.license.secretKeyName }}
          {{- end }}
          - name: LENSESHQ_PG_PASSWORD
            valueFrom:
              secretKeyRef:
              {{- include "validate.singleEnabledDatabase" . -}}
            {{- range $name, $db := .Values.lensesHq.storage }}
              {{- if $db.enabled }}
              {{- if contains "createNew" $db.passwordSecret.type }}
                name: {{ include "databaseSecretName" $ }}
                key: "password"
              {{ else if or (contains "precreated" $db.passwordSecret.type) (contains "externalSecret" $db.passwordSecret.type) }}
                name: {{ $db.passwordSecret.name }}
                key: {{ $db.passwordSecret.key }}
              {{- end }}
          - name: LENSESHQ_PG_USERNAME
            {{- if $db.useSecretForUsername.enabled }}
            valueFrom:
              secretKeyRef:
                name: {{ $db.useSecretForUsername.existingSecret.name }}
                key: {{ $db.useSecretForUsername.existingSecret.key }}
            {{ else }}
            value: {{ $db.username }}
            {{- end }}
          {{- end}}
            {{- end }}

          # Additional env variables
          {{- if .Values.lensesHq.additionalEnv }}
          {{- toYaml .Values.lensesHq.additionalEnv | nindent 10 }}
          {{- end }}

      {{- if .Values.sidecarContainers }}
      {{- toYaml .Values.sidecarContainers | nindent 6 }}
      {{- end }}

      {{- if .Values.initContainers }}
      initContainers:
      {{- toYaml .Values.initContainers | nindent 6 }}
      {{- end }}
