apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{include "fullname" .}}
  labels:
    app: {{include "fullname" .}}
    chart: {{printf "%s-%s" .Chart.Name .Chart.Version}}
    release: {{.Release.Name}}
    heritage: {{.Release.Service}}
    lenses.io/app: {{include "fullname" .}}
    lenses.io/app.type: lenses-hq-externalsecret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: lenses-hq-secrets
    kind: ClusterSecretStore
  target:
    name: lenses-hq-config-secrets
  dataFrom:
    - extract:
        key: {{.Values.lensesHq.databaseConfig.password.ExternalSecret.key}}