{{- if contains "externalSecret" .Values.lensesHq.postgres.passwordSecret.type }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: {{ include "databaseSecretName" . }}
spec:
  dataFrom:
    - extract:
        key: {{ .Values.lensesHq.postgres.passwordSecret.name }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.lensesHq.postgres.passwordSecret.externalSecret.secretStoreRef.clusterSecretStore.name }}
  target:    
    name: {{ .Values.lensesHq.postgres.passwordSecret.name }}
{{- end -}}
