{{- include "validate.singleEnabledDatabase" . -}}
{{- range $name, $db := .Values.lensesHq.storage }}
{{- if $db.enabled }}
{{- if contains "externalSecret" $db.passwordSecret.type }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: {{ include "databaseSecretName" $ }}
  labels:
    app: {{ include "fullname" $ | quote }}
    chart: {{ printf "%s-%s" $.Chart.Name $.Chart.Version }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    component: "lenses-hq"
    lenses.io/app: {{ include "fullname" $ }}
    lenses.io/app.type: lenses-hq-db-secret
spec:
  dataFrom:
    - extract:
        key: {{ $db.passwordSecret.name }}
  secretStoreRef:
    kind: {{ $db.passwordSecret.externalSecret.secretStoreRef.type }}
    name: {{ $db.passwordSecret.externalSecret.secretStoreRef.name }}
  target:
    name: {{ $db.passwordSecret.name }}
{{- end -}}
{{- end -}}
{{- end -}}