{{- if .Values.ingress.http.enabled }}
apiVersion: {{ include "ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "fullname" . }}-http
  labels:
    app: {{ include "fullname" . }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    component: "lenses-hq"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name}}
    lenses.io/app: {{ include "fullname" . }}
    lenses.io/app.type: lenses-hq-ingress
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end}}
  annotations:
  {{- range $key, $value := .Values.ingress.http.annotations}}
    {{$key}}: {{$value | quote}}
  {{- end}}
spec:
  {{- if .Values.ingress.http.ingressClassName}}
  ingressClassName: {{ .Values.ingress.http.ingressClassName | quote}}
  {{- end}}
  rules:
  - host: {{ .Values.ingress.http.host | quote }}
    http:
      paths:
      - path: "/"
        {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress"}}
        pathType: Prefix
        backend:
          service:
            name: {{include "fullname" . | quote}}
            port:
              number: {{.Values.servicePort}}
        {{- else}}
        backend:
          serviceName: {{include "fullname" . | quote}}
          servicePort: {{.Values.servicePort}}
        {{- end}}
  {{- if .Values.ingress.http.tls.enabled}}
  tls:
    - hosts:
      - {{ .Values.ingress.http.host | quote}}
      {{- if .Values.ingress.http.tls.secretName}}
      secretName: {{ .Values.ingress.http.tls.secretName}}
      {{- else}}
      secretName: {{ include "fullname" . | quote}}
      {{- end}}
  {{- end -}}
{{- end -}}
