### https://docs.lenses.io/6.0/installation/getting-started/helm/ ###

nameOverride: ""
fullnameOverride: ""

# -- Image map
# @section -- Custom deployment values
image:
  # -- Image repository
  # @section -- Custom deployment values
  repository: lensting/lenses-agent

  # -- Default to .Chart.AppVersion
  # tag:
  # -- Image pullPolicy
  # @section -- Custom deployment values
  pullPolicy: IfNotPresent
  # -- imagePullSecrets: # any image pull secrets for private registries go here
  #   - name: regcred

# -- (dict) Custom deployment annotations
# @section -- Custom deployment values
annotations: {}
# -- (dict) Annotations here go into the PodTemplateSpec at deployment.spec.template.annotations.
# @section -- Custom deployment values
podTemplateAnnotations: {}
# -- (dict) Deployment labels
# @section -- Custom deployment values
labels: {}
# -- (dict) Deployment strategy
# @section -- Custom deployment values
strategy: {}
# -- (dict) Deployment nodeSelector
# @section -- Custom deployment values
nodeSelector: {}
# -- (dict) Deployment tolerations
# @section -- Custom deployment values
tolerations: {}
# -- (dict) Deployment affinity rules
# @section -- Custom deployment values
affinity: {}
# -- (dict) Deployment security context
# @section -- Custom deployment values
securityContext: {}
# dnsPolicy: "None" # Optional dnsPolicy and dnsConfig to put into the Deployment's PodTemplateSpec.
# dnsConfig:
#   nameservers:
#     - 1.1.1.1
# containerSecurityContext: # Optional, plugged in into the both the deployment's main app container and the sidecar.
#   allowPrivilegeEscalation: false

# Add Prometheus annotations to the pod for Lenses metric scraping
# * The metrics path is '/metrics' and is not adjustable
# * Consumer lag metrics are exposed under 'lenses.url/metrics'. There isn't a standard way to add multiple scrape
#   targets in the annotations, so you will have to add the lag metrics target manually to your Prometheus instance.
monitoring:
  # -- (dict) Enables port on certain port where path /metrics gets exposed.
  # @section -- Monitoring scope values
  enabled: true
  # -- (dict) Sets port where metrics will be exposed
  # @section -- Monitoring scope values
  port: 9102

# Resource management
# Lenses itself is bound by the JVM heap settings ('lenses.jvm.heapOpts' in the chart). The default
# heap space Lenses can use is 3GiB. If you increase the memory resource here, you will need to also
# adjust 'lenses.jvm.heapOpts'. You should allow for 1-2GiB extra space beyond the heap. So if the
# memory limit is 10Gi, set 'lenses.jvm.heapOpts' to '-Xmx8g -Xms4g'.
# -- Pod resources
# @section -- Custom deployment values
resources:
  requests:
  #   cpu: 1
    memory: 4Gi
  limits:
  #   cpu: 2
    memory: 5Gi

# -- (bool) Enables rbac which indicates if a the cluster has rbac enabled and a cluster role
# and clusterrolebinding should be created for the service account
# @section -- Permission scope values
rbacEnable: true

# -- (bool) Enables namespaceScope which indicates that if the cluster has rbac and namespaceScope is enabled
#  role and role binding on namespace level will be created
# @section -- Permission scope values
namespaceScope: true

# -- (int) Lenses Agent container port
# @section -- Lenses Agent deployment service values
restPort: 3030

# -- (string) Lenses Agent service port name
# @section -- Lenses Agent deployment service values
servicePortName: lenses-agent

# -- User to be used by Lenses to deploy apps
# @section -- Permission scope values
serviceAccount:
  # -- (bool) In case "true" new SA will be created with service.name as a SA name.
  # @section -- Permission scope values
  create: false

  # -- (string) Name of Service Account. In case serviceAccount.create is *false*, existing SA with defined name here will be used.
  # @section -- Permission scope values
  name: default

  # -- (dict) Additional service account annotations.
  # @section -- Permission scope values
  annotations: {}

persistence:
  log:
    # -- (boolean) Extra volume creation dedicated for logs.
    # @section -- Persistence scope values
    enabled: true
    # -- (boolean) Annotations dedicated for logs.
    # @section -- Persistence scope values
    annotations: {}
    # -- (list) Access mode rights for created persistence volumes.
    # @section -- Persistence scope values
    accessModes:
      - ReadWriteOnce
    # -- (string) Size of persistence that will be created.
    # @section -- Persistence scope values
    size: 5Gi
  ## Target a pre-existing volume claim to use it as Lenses Persistent volume
  # existingClaim:

  ## Policies data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"

# -- (list) Additional volume mounts to use in Lenses delpoyments, for example to load additional plugins (UDFs) in Lenses
# Use it in conjuction with lenses.additionalVolumes
# @section -- Extras
additionalVolumeMounts:
  # - name: lenses-plugins
  #   mountPath: "/data/plugins"

# -- (list) Additional volumes to use in Lenses delpoyments either by Lenses for other sidecars like Lenses provisioner.
# @section -- Extras
additionalVolumes:
  # Example usages:
  #   Lenses: load additional plugins (UDFs) in Lenses
  #   Lenses provisioner: load additional files from pre-existing volumes, secrets or vault secrets to use in provisioning
  # - name: secrets
  #   secret:
  #     secretName: lenses-super-secrets
  # Note: PersistentVolumeClaim should already exist before deploying Helm chart
  # - name: lenses-plugins
  #   persistentVolumeClaim:
  #     claimName: lenses-plugins

# @section -- Lenses Agent deployment service values
service:
  # -- (bool) Deciding factor whether Lenses HQ service will be created and which type
  # @section -- Lenses Agent deployment service values
  enabled: true

  # -- (dict) Additional service annotations
  # @section -- Lenses Agent deployment service values
  annotations: {}

# Optionally add this property in case you would like to enforce Read Only Root Filesystem
# In that case only /data and /tmp directories will extra mounted and be writable
# the rest will be mount the container's root filesystem as read-only.
containerSecurityContext:
  # -- (list) Enabling read only root filesystem.
  # @section -- Extras
  readOnlyRootFilesystem: false

lensesAgent:
  # Configuration necessary for agent connecting to HQ
  # @section -- Agent <-> HQ scope values
  hq:
    agentKey:
      secret:
        # -- (string) Secret type for referencing / creating agent key
        # Possible values: createNew | precreated | externalSecret
        # @section -- Agent <-> HQ scope values
        type: ""

        ## Value which hold agentKey string and from which secret will be created
        ## necessary only in case secret type is "createNew"
        # value: ""

        ## Key from secret's data where Lenses agent_key is being stored
        key: ""
        ## Secret name where Lenses agent_key will be read from.
        ## Not necessary when externalSecret is being used
        name: ""
        # Required in case secret.type: "externalSecret", alongisde secret.key
        # @section -- Agent <-> HQ scope values
        externalSecret:
          # -- (string) Additional specifications that would enhance `spec:` of created ExternalSecret
          # @section -- Agent <-> HQ scope values
          additionalSpecs: {}
          secretStoreRef:
            # -- (string) Type of secret store created by ESO.
            # @section -- Agent <-> HQ scope values
            type: ""
            # -- (string) Name of cluster secret store created by ESO.
            # @section -- Agent <-> HQ scope values
            name: ""

        ## Required in case secret.type: "precreated": name & key
        # type: "precreated"
        # name: "secret-name"
        # key: "secret-key"

  provision:
    # -- (string) Path where provisioner will be initiated.
    # @section -- Agent Provision scope values
    path: /mnt/provision-secrets
    # Find more details in https://docs.lenses.io/5.5/installation/getting-started/helm/#helm-provision

    # You can find examples at https://github.com/lensesio/lenses-helm-charts/tree/release/5.5/examples
    connections:
      #  lensesHq:
      #    - name: lenses-hq
      #      version: 1
      #      tags: ['hq']
      #      configuration:
      #        server:
      #          value: panoptes-backend.panoptes-master.svc.cluster.local
      #        port:
      #          value: 10000
      #        agentKey:
      #          value: ${LENSESHQ_AGENT_KEY}
      #        sslEnabled:
      #          value: false
      #        sslEnabledProtocols:
      #          value: $LENSES_HQ_SSL_ENABLED_PROTOCOLS
      #kafka:
      #  - name: kafka
      #    version: 1
      #    tags: [ 'prod']
      #    configuration:
      #      kafkaBootstrapServers:
      #        value:
      #          - SASL_PLAINTEXT://kafka:9092
      #      saslJaasConfig:
      #        value: org.apache.kafka.common.security.scram.ScramLoginModule required username="user1" password="insert-pwd-here";
      #      saslMechanism:
      #        value: SCRAM-SHA-256
      #      protocol:
      #        value: SASL_PLAINTEXT
      #      metricsType:
      #        value: JMX
      #      metricsPort:
      #        value: 9581
      # confluentSchemaRegistry:
      #   - name: schema-registry
      #     version: 1
      #     tags: [ 'prod' ]
      #     configuration:
      #       schemaRegistryUrls:
      #         value:
      #           - http://schema-registry-1.svc.cluster.local:8081
      # connect:
      #   - name: datalake-connect
      #     version: 1
      #     tags: [ 'prod', 'datalake' ]
      #     configuration:
      #       workers:
      #         value:
      #           - http://connect-worker-1.svc.cluster.local:8083
      #       metricsType:
      #         value: JMX
      #       metricsPort:
      #         value: 9584
    # -- (dict) Secrets base64 encoded (such as keystores) which will be placed within provisioner folder upon initialisation.
    # @section -- Agent Provision scope values
    secrets: {}
      # Base64 encoded. Read how to convert from .pem to .jks in the article: https://docs.lenses.io/current/configuration/dynamic/pem-to-jks-conversion/
      # data:
      #   kafka.keystore.jks: |-
      #   kafka.truststore.jks: |-
      # stringData:

  # For additional generic JVM settings
  # Read more: https://docs.lenses.io/current/configuration/static/jvm/
  # -- (string) For additional generic JVM settings
  # @section -- Extras
  lensesOpts: |-

  # Each version of the helm chart for Lenses is accompanied by a values.yaml.
  # This values file contains sane defaults for all the supported Lenses configuration options for that version of the chart.
  # Although great care has been taken to cover most use cases in the chart, we may encounter situations where a specific configuration option is required but is not available.
  # To support such cases, Lenses Helm Chart provides the lenses.append.conf mechanism.
  append:
    # Custom configuration values, will take precedence over the env variables and auto-generated values
    # Read more: https://help.lenses.io/knowledge-base/helm/helm-lenses-append-conf/
    # -- (string) Additional parameters which usually go to lenses.conf and are not supported by this Helm Chart.
    # @section -- Extras
    conf: |-

  jvm:
    # -- (string) heapOpts are any overrides for Lenses Heap JVM options.
    # Please adjust this in sync with 'resources.limits.memory'
    # @section -- Agent JVM scope values
    heapOpts:
    # -- (string) logBackOpts are any logging options. Lenses is using the logback library.
    # @section -- Agent JVM scope values
    logBackOpts:

    # -- (string) performanceOpts are any jvm tuning options to add to the jvm
    # @section -- Agent JVM scope values
    performanceOpts:

  # Override the default logback xml
  # Used primarily to load a Lenses provided xml with debug level set for Lenses libs
  # Can be used to load your custom logback if needed. Uncomment the following line
  # to switch the log level for Lenses facilities to DEBUG.
  # logbackXml: /opt/lenses/logback-debug.xml

  # -- (string) Global truststore/keystore for the JVM.
  # base64 encoded truststore data
  # openssl base64 < kafka.truststore.jks | tr -d '\n'
  # @section -- Agent JVM scope values
  opts:

    trustStoreFileData: |-

    trustStorePassword: |-

  # Find more details in https://docs.lenses.io/current/installation/kubernetes/helm/#helm-storage
  storage:
    # -- (dict) Connection details for Postgres database
    # @section -- Agent Database scope values
    postgres:
      # -- (boolean) Enables postgres database connection, otherwise H2 as internal database will be used.
      # @section -- Agent Database scope values
      enabled: false
      # -- (string) Postgres database host details
      # @section -- Agent Database scope values
      host:
      # -- (int) Postgres database port details
      # @section -- Agent Database scope values
      port:               # optional, defaults to 5432

      # Set the username for postgres connection
      # Use the value "external" to bypass the Helm validation and handle the username externally.
      # The common use case for using "external" is to take the actual value from a Kubernetes Secret resource already deployed.
      # To do so, add the following definition under 'lensesAgent.additionalEnv' key:
      # - name: LENSES_STORAGE_POSTGRES_USERNAME
      #   valueFrom:
      #     secretKeyRef:
      #       name: [SECRET_RESOURCE_NAME]
      #       key: [SECRET_RESOURCE_KEY]
      # -- (string) Postgres database user details
      # @section -- Agent Database scope values
      username:           # use "external" to manage it using secrets

      # Set the password for postgres connection
      # Use the value "external" to bypass the Helm validation and handle the password externally.
      # The common use case for using "external" is to take the actual value from a Kubernetes Secret resource already deployed.
      # To do so, add the following definition under 'lensesAgent.additionalEnv' key:
      # - name: LENSES_STORAGE_POSTGRES_PASSWORD
      #   valueFrom:
      #     secretKeyRef:
      #       name: [SECRET_RESOURCE_NAME]
      #       key: [SECRET_RESOURCE_KEY]
      # -- (string) Postgres user password details
      # @section -- Agent Database scope values
      password:           # use "external" to manage it using secrets
      # -- (string) Postgres database name that Agent will connect to and communicate with.
      # @section -- Agent Database scope values
      database:
      # -- (string) Postgres schema, defaults to public in case not defined.
      # @section -- Agent Database scope values
      schema:             # optional, defaults to public schema

  sql:
    # processorImage: lensesioextra/sql-processor
    # processorImageTag: 5.5

    # -- (string) Setting execution mode for SQL Processors
    # Example: IN_PROC | KUBERNETES
    # @section -- Agent SQL Processor scope values
    mode: IN_PROC

    # -- (string) Setting heap for each individual SQL Processor
    # @section -- Agent SQL Processor scope values
    heap: 1024M

    # -- (string) Setting min heap for each individual SQL Processor
    # @section -- Agent SQL Processor scope values
    minHeap: 128M

    # -- (string) Setting memory limit for each individual SQL Processor
    # @section -- Agent SQL Processor scope values
    memLimit: 1152M

    # -- (string) Setting memory limit for each individual SQL Processor
    # @section -- Agent SQL Processor scope values
    memRequest: 128M

    # -- (string) Setting initial delay when SQL processor is being started
    # @section -- Agent SQL Processor scope values
    livenessInitialDelay: 60 seconds

  # -- (string) URL for Grafana UI
  # @section -- Extras
  grafanaUrl:

  topics:
    # -- (string) Suffix to add to lenses system topics, for example if you are running more than one Lenses on the same kafka cluster
    # @section -- Extras
    suffix:

  # -- (string) Additional env variables appended to deployment
  # @section -- Extras
  # Follows the format of [EnvVar spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#envvar-v1-core)
  additionalEnv:
    # - name: FOO
    #   value: bar

  livenessProbe:
    # -- (string) Disables livenessProbe, used while debugging
    # @section -- Extras
    enabled: true

  pauseExec:
    # -- (string) Pauses execution of Lenses start up script to allow the user to login into the container and
    # check the running environment, used while debugging
    # @section -- Extras
    enabled: false

# -- (map) Sidecar container enablement.
# @raw
#
# sidecarContainers:
  # - name: sidecar-example
  #   image: alpine
  #   command: ["sh", "-c", "watch date"]

# initContainers:
#   - name: init-example
#     image: alpine
#     command: ["sh", "-c", "date"]
