{{- if and .Values.persistence.log.enabled (not .Values.persistence.existingClaim) -}}

apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: {{include "logsClaimName" .}}
{{- if .Values.persistence.annotations}}
  annotations:
{{toYaml .Values.persistence.annotations | indent 4}}
{{- end }}
  labels:
    app: {{include "name" .}}
    chart: {{printf "%s-%s" .Chart.Name .Chart.Version}}
    component: "lenses"
    heritage: {{.Release.Service}}
    release: {{.Release.Name}}
    lenses.io/app: {{include "name" .}}
    lenses.io/app.type: lenses-volume-claim
spec:
  accessModes:
{{toYaml .Values.persistence.accessModes | indent 4}}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass)}}
  storageClassName: ""
{{- else }}
  storageClassName: {{.Values.persistence.storageClass}}
{{- end }}
{{- end }}
  resources:
    requests:
{{- if and (hasKey .Values.persistence "log") (hasKey .Values.persistence.log "size")}}
     storage: {{.Values.persistence.log.size | quote}}
{{- else }}
     storage: "300Mi"
{{- end -}}

{{- end -}}
