{{- if and .Values.lenses.provision.enabled (eq .Values.lenses.provision.version "2")}}
kind: Secret
apiVersion: v1
metadata:
  name: {{include "provisionFullname" .}}-files
  labels:
    app: {{include "fullname" .}}
    chart: {{printf "%s-%s" .Chart.Name .Chart.Version}}
    release: {{.Release.Name}}
    heritage: {{.Release.Service}}
    lenses.io/app: {{include "fullname" .}}
    lenses.io/app.type: lenses-provision-secret
data:
{{- if .Values.lenses.provision.secrets.data}}
  {{- toYaml .Values.lenses.provision.secrets.data | nindent 2}}
{{- end}}
stringData:
{{- if .Values.lenses.provision.secrets.stringData}}
  {{- toYaml .Values.lenses.provision.secrets.stringData | nindent 2}}
{{- end}}
{{- end}}
