{{- if and .Values.lenses.provision.enabled (eq .Values.lenses.provision.version "2")}}
kind: Secret
apiVersion: v1
metadata:
  name: {{include "provisionFullname" .}}
  labels:
    app: {{include "fullname" .}}
    chart: {{printf "%s-%s" .Chart.Name .Chart.Version}}
    release: {{.Release.Name}}
    heritage: {{.Release.Service}}
    lenses.io/app: {{include "fullname" .}}
    lenses.io/app.type: lenses-provision-secret
stringData:
  license.json: |
    {{- $license := (required "license.json is required to provision Lenses" .Values.lenses.provision.license) -}}
    {{- kindIs "map" $license | ternary (toJson $license) $license | nindent 4 }}
  provisioning.yaml: |
    {{- toYaml (required "provisioning connections is required to provision Lenses" .Values.lenses.provision.connections) | nindent 4}}
{{- end}}
