{{- if contains "createNew" .Values.lenses.hq.agentKey.secret.type }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentKeySecretName" . }}
  labels:
    app: {{ include "fullname" . | quote }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: "lenses-agent"
    lenses.io/app: {{ include "fullname" . }}
    lenses.io/app.type: lenses-agent-hq-key-secret
type: Opaque
data:
  key: {{ .Values.lenses.hq.agentKey.secret.value | b64enc }}
{{- end }}
