{{- if contains "externalSecret" .Values.lensesAgent.hq.agentKey.secret.type }}
apiVersion: "external-secrets.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "agentKeySecretName" . }}
spec:
{{- range $key, $value := .Values.lensesAgent.hq.agentKey.secret.externalSecret.additionalSpecs }}
  {{ $key }}: {{$value | quote }}
{{- end }}
  dataFrom:
    - extract:
        key: {{ .Values.lensesAgent.hq.agentKey.secret.name }}
  secretStoreRef:
    kind: {{ .Values.lensesAgent.hq.agentKey.secret.externalSecret.secretStoreRef.type }}
    name: {{ .Values.lensesAgent.hq.agentKey.secret.externalSecret.secretStoreRef.name }}
  target:
    name: {{ .Values.lensesAgent.hq.agentKey.secret.name }}
    creationPolicy: {{ .Values.lensesAgent.hq.agentKey.secret.externalSecret.creationPolicy }}
{{- end -}}
