{{- if contains "externalSecret" .Values.lenses.hq.agentKey.secret.type }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: {{ include "agentKeySecretName" . }}
spec:
  dataFrom:
    - extract:
        key: {{ .Values.lenses.hq.agentKey.secret.key }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.lenses.hq.agentKey.secret.externalSecret.secretStoreRef.clusterSecretStore.name }}
  target:
    name: {{ include "agentKeySecretName" . }}
{{- end -}}
