{{- if and .Values.rbacEnable (not .Values.namespaceScope) }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "fullname" . }}
  labels:
    app: {{ include "fullname" . }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    lenses.io/app: {{ include "fullname" . }}
    lenses.io/app.type: lenses-agent-cluster-role
rules:
- apiGroups: [""]
  resources:
    - namespaces
  verbs:
    - list
    - watch
    - get
- apiGroups: [""]
  resources:
    - configmaps
    - pods
    - secrets
    - services
  verbs:
    - list
    - watch
    - get
    - update
    - create
    - delete
    - patch
- apiGroups: ["apps"]
  resources:
    - replicasets
    - deployments
    - deployments/scale
    - statefulsets
  verbs:
    - list
    - watch
    - get
    - update
    - create
    - delete
    - patch
- apiGroups: [""]
  resources:
    - pods/log
  verbs:
    - get
- apiGroups: [""]
  resources:
    - events
  verbs:
    - list
    - watch
    - get
{{- end }}
