{{- if and .Values.persistence.log.enabled (not .Values.persistence.log.existingClaim) -}}

apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: {{ include "logsClaimName" . }}
{{- if .Values.persistence.log.annotations}}
  annotations:
{{toYaml .Values.persistence.log.annotations | indent 4}}
{{- end }}
  labels:
    app: {{include "name" .}}
    chart: {{printf "%s-%s" .Chart.Name .Chart.Version}}
    component: "lenses-agent"
    heritage: {{.Release.Service}}
    release: {{.Release.Name}}
    lenses.io/app: {{include "name" .}}
    lenses.io/app.type: lenses-agent-logs-volume-claim
spec:
  accessModes:
{{toYaml .Values.persistence.log.accessModes | indent 4}}
{{- if .Values.persistence.log.storageClass }}
{{- if (eq "-" .Values.persistence.log.storageClass)}}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .Values.persistence.log.storageClass }}
{{- end }}
{{- end }}
  resources:
    requests:
{{- if and (hasKey .Values.persistence "log") (hasKey .Values.persistence.log "size")}}
     storage: {{ .Values.persistence.log.size | quote }}
{{- else }}
     storage: "300Mi"
{{- end -}}

{{- end -}}
