{{- if and .Values.lensesAgent.provision.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "provisionFullname" . }}-files
  labels:
    app: {{ include "fullname" . }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    lenses.io/app: {{ include "fullname" . }}
    lenses.io/app.type: lenses-agent-provision-secretå
data:
{{- if .Values.lensesAgent.provision.secrets.data }}
  {{- toYaml .Values.lensesAgent.provision.secrets.data | nindent 2 }}
{{- end}}
stringData:
{{- if .Values.lensesAgent.provision.secrets.stringData }}
  {{- toYaml .Values.lensesAgent.provision.secrets.stringData | nindent 2 }}
{{- end}}
{{- end}}
