kind: Secret
apiVersion: v1
metadata:
  name: {{include "provisionFullname" .}}
  labels:
    app: {{include "fullname" .}}
    chart: {{printf "%s-%s" .Chart.Name .Chart.Version}}
    release: {{.Release.Name}}
    heritage: {{.Release.Service}}
    lenses.io/app: {{include "fullname" .}}
    lenses.io/app.type: lenses-agent-provision-secret
stringData:
  provisioning.yaml: |
    {{- toYaml (required "provisioning connections is required to provision Lenses" .Values.lensesAgent.provision.connections) | nindent 4}}