kind: Secret
apiVersion: v1
metadata:
  name: {{ include "fullname" . }}
  labels:
    app: {{ include "fullname" . }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    lenses.io/app: {{ include "fullname" . }}
    lenses.io/app.type: lenses-agent-secret
data:
  lenses.opts.truststore.jks: |-
    {{- .Values.lensesAgent.opts.trustStoreFileData | default "" | nindent 4}}

stringData:
  {{- if .Values.lensesAgent.opts.trustStoreFileData }}
  lenses.opts.truststore.password: {{ required "When you set trustStoreFileData, you also need to set trustStorePassword" .Values.lensesAgent.opts.trustStorePassword | quote }}
  {{- end}}

  {{- if .Values.lensesAgent.jvm.trustStoreFileData }}
  {{/* Deliberately fail helm deployment */}}
  {{ required ".Values.lensesAgent.jvm.trustStoreFileData is deprecated in favor of Values.lensesAgent.opts.trustStoreFileData, please use the latter." nil }}
  {{- end}}
  {{- if .Values.lensesAgent.jvm.trustStorePassword }}
  {{/* Deliberately fail helm deployment */}}
  {{ required ".Values.lensesAgent.jvm.trustStorePassword is deprecated in favor of Values.lensesAgent.opts.trustStorePassword, please use the latter." nil }}
  {{- end}}
