{{ if .Values.service.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "fullname" . }}
  labels:
    app: {{ include "fullname" . }}
    chart: {{.Chart.Name}}-{{ .Chart.Version }}
    component: "lenses-agent"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    lenses.io/app: {{ include "fullname" . }}
    lenses.io/app.type: lenses-agent-service
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type | quote }}
  ports:
  - name: http-metrics
    port: {{ .Values.monitoring.port }}
  - name: lenses-agent-rest
    port: {{ .Values.restPort}}
  selector:
    app: {{ include "fullname" . }}
    component: "lenses"

{{- end -}}
