apiVersion: v1
description: A chart for Lenses HQ deployment which provides a unified, streamlined view of the entire event infrastructure—whether on-premises or in the cloud—through a single, comprehensive interface.
icon: https://www.lenses.io/images/logos/icon_ellipse2red.png
name: lenses-hq
version: 6.0.4
appVersion: 6.0.4
