image:
  repository: lensesiolocal/lenses-hq

ingress:
  host: lenses.url
lensesHq:
  agents:
    address: ""
    tls:
      enabled: false
  postgres:
    passwordSecret:
      key: lenses-db-secret
