nameOverride: ""
fullnameOverride: ""

# -- (dict) Custom deployment annotations
# @section -- Custom deployment values
annotations: {}
# -- (dict) Annotations here go into the PodTemplateSpec at deployment.spec.template.annotations.
# @section -- Custom deployment values
podTemplateAnnotations: {}
# -- (dict) Deployment labels
# @section -- Custom deployment values
labels: {}
# -- (dict) Deployment strategy
# @section -- Custom deployment values
strategy: {}
# -- (dict) Deployment nodeSelector
# @section -- Custom deployment values
nodeSelector: {}
# -- (dict) Deployment tolerations
# @section -- Custom deployment values
tolerations: []
# -- (dict) Deployment affinity rules
# @section -- Custom deployment values
affinity: {}
# -- (dict) Deployment security context
# @section -- Custom deployment values
securityContext: {}
# dnsPolicy: "None" # Optional dnsPolicy and dnsConfig to put into the Deployment's PodTemplateSpec.
# dnsConfig:
#   nameservers:
#     - 1.1.1.1
# containerSecurityContext: # Optional, plugged in into the both the deployment's main app container and the sidecar.
#   allowPrivilegeEscalation: false

# Add Prometheus annotations to the pod for Lenses metric scraping
# * The metrics path is '/metrics' and is not adjustable

#  Resource management
# -- Pod resources
# @section -- Custom deployment values
resources:
  requests:
  #   cpu: 1
    memory: 4Gi
  limits:
  #   cpu: 2
    memory: 5Gi
# -- Image map
# @section -- Custom deployment values
image:
  # -- Image repository
  # @section -- Custom deployment values
  repository: ""

  # -- Default to .Chart.AppVersion
  # tag:
  # -- Image pullPolicy
  # @section -- Custom deployment values
  pullPolicy: IfNotPresent
  # -- imagePullSecrets: # any image pull secrets for private registries go here
  #   - name: regcred

# -- (bool) rbacEnable indicates if a the cluster has rbac enabled and a cluster role  and rolebinding should be created for the service account
# @section -- Permission scope values
rbacEnable: true

# -- (bool)  In case rbac is enabled you can choose to enable creation on namespace scoped roles
# instead of cluster roles instead
# @section -- Permission scope values
namespaceScope: true

# -- (int) Lenses HQ service port, service targets restPort
# @section -- Lenses HQ deployment service values
servicePort: 80
# -- (string) Lenses HQ service port name
# @section -- Lenses HQ deployment service values
servicePortName: lenses-hq

# -- User to be used by Lenses to deploy apps
# @section -- Permission scope values
serviceAccount:
  # -- (bool) In case "true" new SA will be created with service.name as a SA name.
  # @section -- Permission scope values
  create: false

  # -- (string) Name of Service Account. In case serviceAccount.create is *false*, existing SA with defined name here will be used.
  # @section -- Permission scope values
  name: lenses

  # -- (dict) Additional service account annotations.
  # @section -- Permission scope values
  annotations: {}

# @section -- Lenses HQ deployment service values
service:
  # -- (bool) Deciding factor whether Lenses HQ service will be created and which type
  # @section -- Lenses HQ deployment service values
  enabled: true

  # -- (string) Type of service to be created.
  # @section -- Lenses HQ deployment service values
  type: ClusterIP

  # -- (dict) Additional service annotations
  # @section -- Lenses HQ deployment service values
  annotations: {}

  # If you want to make it available as a node port, then add nodePort: <somePort>
  # Warning: this should not be used with servicePort:
  # Warning nodePort is deprecated and will be removed on next Lenses major version upgrade
  # nodePort:
  # -- (string)
  # @section -- Lenses HQ deployment service values
  externalTrafficPolicy:

  ## Load balancer IP address
  ## Is not required, but allows for static address with
  ## serviceType LoadBalancer.
  ## If not supported by cloud provider, this field is ignored.
  ## Default: nil
  ##
  # loadBalancerIP: 130.211.x.x

  ## This will restrict traffic through the cloud-provider load-balancer
  ## to the specified client IPs.
  ## If not supported by cloud provider, this field is ignored.
  ## Default: nil
  ##
  # loadBalancerSourceRanges:
  #   - 0.0.0.0/0

ingress:
  agent:
    # -- (bool) If true, Ingress will be created
    # @section -- Lenses HQ Agent Ingress deployment service values
    enabled: false
    # -- (string) Object defines the Kubernetes Ingress resource for the agent, including the apiVersion, kind, metadata (e.g., name),
    #  and spec with routing rules, host, HTTP paths, and the backend service details (name and port).
    # @section -- Lenses HQ Agent Ingress deployment service values
    agentIngressConfig: {}


  http:
    # -- (bool) If true, Ingress will be created
    # @section -- Lenses HQ HTTP API deployment service values
    enabled: false

    # -- (tpl/string) Set custom host name. (DNS name convention)
    # @notationType -- tpl
    # @section -- Lenses HQ HTTP API deployment service values
    host: ""

    # @notationType -- tpl
    # @section -- Lenses HQ HTTP API deployment service values
    ingressClassName: ""

    # -- (dict) Custom Ingress annotations
    # @section -- Lenses HQ HTTP API deployment service values
    annotations: {}
      # Optionally add here the annotations related to the ingress provider, see examples below:
      # kubernetes.io/ingress.class: traefik
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: 'true'
      # nginx.ingress.kubernetes.io/rewrite-target: /

    # -- TLS if enabled load the tls.crt and tls.keys as a secrets and enable TLS on the ingress
    # @section -- Lenses HQ HTTP API deployment service values
    tls:
      # -- (bool) Set to true to enable HTTPS
      # @section -- Lenses HQ HTTP API deployment service values
      enabled: false

      # -- (string) Secret name where tls certificates are being stored.
      # The TLS secret must contain keys named tls.crt and tls.key that contain the certificate and private key to use for TLS.
      # @section -- Lenses HQ HTTP API deployment service values
      secretName: ""

lensesHq:
  agents:
    # -- (string) Address wherefrom agent will be listening at.
    # @section -- Lenses HQ Agent startup values
    # **Required: true**
    address: ":10000"

    tls:
      # -- (string) Enables or disables TLS.
      # @section -- Lenses HQ Agent startup values
      # **Required: true**
      enabled: false

      # -- (string) Enabled verbose of TLS debug logs
      # @section -- Lenses HQ Agent startup values
      # **Required: true**
      verboseLogs: false

      cert:
        # -- (string) Enables usage of secret for certificate.
        # @section -- Lenses HQ Agent startup values
        # **Required: false**
        referenceFromSecret: false
        # -- (string) Secret name where certificate is stored.
        # @section -- Lenses HQ Agent startup values
        # **Required: false**
        secretName: ""
        # -- (string) Secret key where within a secret where certificate is sotred.
        # @section -- Lenses HQ Agent startup values
        # **Required: false**
        secretKeyName: ""
        # -- (string) Sets the PEM formatted public certificate.
        # @section -- Lenses HQ Agent startup values
        # **Required: false**
        stringData: |

      # -- (string) Sets the PEM formatted private key.
      # @section -- Lenses HQ Agent startup values
      # **Required: false**
      privateKey:
        # Reference to precreated secret name and key.
        secret:
          name: ""
          key: ""

  auth:
    # -- Grants administrator rights to users.
    # @section -- Lenses HQ AUTH startup values
    # **Required: false**
    administrators: []

    # -- Adds uses for password based auth
    # @section -- Lenses HQ AUTH startup values
    # **Required: false**
    users: []

    # -- (string) # Sets the duration of a session. The duration is a
    # string that follows the Go time.Duration format. Valid time units are "ns",
    # "us" (or "µs"), "ms", "s", "m", "h". The duration is used to set the
    # expiration time of the session cookie.
    # @section -- Lenses HQ SAML startup values
    # **Required: false**
    sessionDuration: "24h"


    saml:
      # -- Enables SAML / SSO authentication
      # @section -- Lenses HQ SAML startup values
      # **Required: true**
      enabled: false
      # -- Defines base URL of Panoptes for IdP redirects.
      # @section -- Lenses HQ SAML startup values
      # **Required: true**
      baseURL: ""

      # -- Defines the Entity ID.
      # @section -- Lenses HQ SAML startup values
      # **Required: true**
      entityID: ""

      # -- Contains the IdP issued XML metadata blob.
      # Example: <?xml version="1.0" ... (big blob of xml) </md:EntityDescriptor>
      # @section -- Lenses HQ SAML startup values
      # **Required: true**
      metadata:
        # -- (boolean) Enables use of configmap to refernence SAML metadata file.
        # @section -- Lenses HQ SAML startup values
        # **Required: true**
        referenceFromSecret: false
        # -- (string) ConfigMap name which contains metadata information.
        # @section -- Lenses HQ SAML startup values
        # **Required: false**
        secretName: ""
        # -- (string) ConfigMap key used to reference configmap metadata information.
        # @section -- Lenses HQ SAML startup values
        # **Required: false**
        secretKeyName: "metadata.xml"
        # -- Contains the IdP issued XML metadata blob.
        # Example: <?xml version="1.0" ... (big blob of xml) </md:EntityDescriptor>
        # @section -- Lenses HQ SAML startup values
        # **Required: true**
        stringData: |

      # -- Controls how the creation of users should be handled in relation to SSO information
      # Allowed values are: sso | manual
      # @section -- Lenses HQ SAML startup values
      # **Required: false**
      userCreationMode: "manual"

      # -- Controls how the management of a user's group membership should be handled in relation to SSO information.
      # Allowed values are: sso | manual
      # @section -- Lenses HQ SAML startup values
      # **Required: false**
      usersGroupMembershipManagementMode: "manual"

      # -- Controls where to redirect to upon successful authentication.
      # @section -- Lenses HQ SAML startup values
      # **Required: false**
      uiRootURL: "/"

      # -- Sets the attribute name for group names.
      # @section -- Lenses HQ SAML startup values
      # **Required: false**
      groupAttributeKey: "groups"


  http:
    # -- (string) Sets the address the HTTP servers listens at.
    # @section -- Lenses HQ HTTP startup values
    # **Required: true**
    address: ":8080"

    # -- (string) Sets the address the HTTP server listens at.
    # @section -- Lenses HQ HTTP startup values
    # **Required: false**
    accessControlAllowOrigin: []

    # -- Sets the value of the "Access-Control-Allow-Credentials" header.
    # @section -- Lenses HQ HTTP startup values
    # **Required: false**
    accessControlAllowCredentials: false

    # -- Sets the "Secure" attribute on session cookies.
    # @section -- Lenses HQ HTTP startup values
    # **Required: false**
    secureSessionCookies: true

    tls:
      # -- (string) Enables or disables TLS.
      # @section -- Lenses HQ HTTP startup values
      # **Required: true**
      enabled: false

      # -- (string) Enabled verbose of TLS debug logs
      # @section -- Lenses HQ HTTP startup values
      # **Required: true**
      verboseLogs: false

      cert:
        # -- (string) Enables usage of secret for certificate.
        # @section -- Lenses HQ HTTP startup values
        # **Required: false**
        referenceFromSecret: false
        # -- (string) Secret name where certificate is stored.
        # @section -- Lenses HQ HTTP startup values
        # **Required: false**
        secretName: ""
        # -- (string) Secret key where within a secret where certificate is sotred.
        # @section -- Lenses HQ HTTP startup values
        # **Required: false**
        secretKeyName: ""
        # -- (string) Sets the PEM formatted public certificate.
        # @section -- Lenses HQ HTTP startup values
        # **Required: false**
        stringData: |

      # -- (string) Sets the PEM formatted private key.
      # @section -- Lenses HQ HTTP startup values
      # **Required: false**
      privateKey:
        # Reference to precreated secret name and key.
        secret:
          name: ""
          key: ""

  storage:
    postgres:
      # -- (string) Enabling postgres engine. This flag is here as there might be support of multiple database engines in the future.
      # @section -- Lenses HQ Database startup values
      # **Required: true**
      enabled: true
      # -- (string) Hostname of running database instance.
      # @section -- Lenses HQ Database startup values
      # **Required: true**
      host: ""

      # -- (int) Port of running postgress instance. Default is 5432.
      # @section -- Lenses HQ Database startup values
      # **Required: true**
      port: 5432

      # -- (string) Username which will be used for connecting to database database.
      # @section -- Lenses HQ Database startup values
      # **Required: true**
      username: ""

      useSecretForUsername:
        # -- (string) Whether username will be used within a secret or as a part of `username` value.
        # @section -- Lenses HQ Database startup values
        # **Required: true**
        enabled: false
        # -- (string) Secret reference for database user.
        # @section -- Lenses HQ Database startup values
        # **Required: false**
        existingSecret:
          name: ""
          key: ""

      # -- (string) Database name to which HQ will connect to and store required information.
      # @section -- Lenses HQ Database startup values
      # **Required: true**
      database: ""

      # -- (string) Database schema to which HQ will connect to and store required information.
      # @section -- Lenses HQ Database startup values
      # **Required: true**
      schema: ""

      # -- (string) Enables TLS. In PostgreSQL connection string terms, setting TLS to
      #        `false` corresponds to `sslmode=disable`; setting TLS to `true`
      #        corresponds to `sslmode=verify-full`. For more fine-grained control,
      #        specify `sslmode` in the params which takes precedence.
      # @section -- Lenses HQ Database startup values
      # **Required: true**
      tls: false

      # -- (string) Contains connection string parameters as key/values pairs. It allows
      #    fine-grained control of connection settings. The parameters can be found
      #    here: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS
      # @section -- Lenses HQ Database startup values
      # **Required: false**
      params: {}

      # -- Definition of secret that has been precreated and has postgres database password
      # @section -- Lenses HQ Database startup values
      passwordSecret:
        # -- (string) Possible options: precreated | createNew | externalSecret
        # @section -- Lenses HQ Database startup values
        type: "precreated"

        # -- (string) Secret name where database password will be stored in case "createNew" or read from in case of "precreated" | "externalSecret".
        # @section -- Lenses HQ Database startup values
        name: ""

        # -- (string) Entry for a password in case of testing where type: "createNew", otherwise can be left out. *NOT FOR PRODUCTION USE!*
        # @section -- Lenses HQ Database startup values
        password: ""

        # -- (string) Secret key where password will be read from
        # @section -- Lenses HQ Database startup values
        key:
        externalSecret:
          secretStoreRef:
            clusterSecretStore:
              # -- (string) Name of cluster secret store created by ESO.
              # @section -- Lenses HQ Database startup values
              name:

  # @section -- Lenses HQ startup values
  logger:
    # -- (string) Controls the format of the logger's output. Allowed values are: text | json
    # @section -- Lenses HQ logger startup values
    # **Required: true**
    mode: "text"

    # -- (string) Controls the level of the logger
    # Allowed values are: info | debug
    # @section -- Lenses HQ logger startup values
    # **Required: false**
    level: "info"

  metrics:
    # -- (string) ets the address at which Prometheus metrics are served.
    # If not set, it will default to `:9090``
    # @section -- Lenses HQ metrics startup values
    # **Required: false**
    prometheusAddress: ":9090"

  # @section -- Lenses HQ license values
  license:
    # -- (string) Enables usage of secret for license.
    # @section -- Lenses HQ license values
    # **Required: false**
    referenceFromSecret: false
    # -- (string) Secret name where license is stored.
    # @section -- Lenses HQ license values
    # **Required: false**
    secretName: ""
    # -- (string) Secret key where within a secret where license is sotred.
    # @section -- Lenses HQ license values
    # **Required: false**
    secretKeyName: ""
    # -- (string) Sets the license as a stirng.
    # @section -- Lenses HQ license values
    # **Required: false**
    stringData: ""
    # -- (string) Boolean 'acceptEULA' marks the end-user license agreement (EULA) as accepted.
    # You can find the EULA at: https://lenses.io/legals/eula.
    # @section -- Lenses HQ license values
    # **Required: false**
    acceptEULA: false

  # @section -- Lenses HQ startup values
  # Disable livenessProbe, used while debugging
  livenessProbe:
    # -- (bool)
    # @section -- Lenses HQ startup values
    enabled: true
    tls:
      # -- Enabling HTTPS forliveness probe.
      # @section -- Lenses HQ startup values
      enabled: false

  # -- (string) Additional env variables appended to deployment
  # @section -- Extras
  # Follows the format of [EnvVar spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#envvar-v1-core)
  additionalEnv: []
    # - name: FOO
    #   value: bar

# -- (map) Sidecar container enablement.
# @raw
#
# sidecarContainers:
  # - name: sidecar-example
  #   image: alpine
  #   command: ["sh", "-c", "watch date"]

# initContainers:
#   - name: init-example
#     image: alpine
#     command: ["sh", "-c", "date"]