nameOverride: ""
fullnameOverride: ""

annotations: {}
podTemplateAnnotations: {} # Annotations here go into the PodTemplateSpec at deployment.spec.template.annotations.
labels: {}
strategy: {}
nodeSelector: {}
tolerations: {}
affinity: {}
securityContext: {}
# dnsPolicy: "None" # Optional dnsPolicy and dnsConfig to put into the Deployment's PodTemplateSpec.
# dnsConfig:
#   nameservers:
#     - 1.1.1.1
# containerSecurityContext: # Optional, plugged in into the both the deployment's main app container and the sidecar.
#   allowPrivilegeEscalation: false

# Add Prometheus annotations to the pod for Lenses metric scraping
# * The metrics path is '/metrics' and is not adjustable
# * Consumer lag metrics are exposed under 'lenses.url/metrics'. There isn't a standard way to add multiple scrape
#   targets in the annotations, so you will have to add the lag metrics target manually to your Prometheus instance.

# Resource management
# Lenses itself is bound by the JVM heap settings ('lenses.jvm.heapOpts' in the chart). The default
# heap space Lenses can use is 3GiB. If you increase the memory resource here, you will need to also
# adjust 'lenses.jvm.heapOpts'. You should allow for 1-2GiB extra space beyond the heap. So if the
# memory limit is 10Gi, set 'lenses.jvm.heapOpts' to '-Xmx8g -Xms4g'.
resources:
  requests:
  #   cpu: 1
    memory: 4Gi
  limits:
  #   cpu: 2
    memory: 5Gi

image:
  name:
  repository: 
  # -- Default to .Chart.AppVersion
  # tag:
  pullPolicy: IfNotPresent
  # -- imagePullSecrets: # any image pull secrets for private registries go here
  #   - name: regcred

# rbacEnable indicates if a the cluster has rbac enabled and a cluster role
# and rolebinding should be created for the service account
rbacEnable: true

# In case rbac is enabled you can choose to enable namespace scoped roles or 
# cluster roles to be created 
namespaceScope: true

# Lenses container port
restPort: 3030
# Lenses service port, service targets restPort
servicePort: 80
servicePortName: lenses-hq

# -- serviceAccount is the Service account to be used by Lenses to deploy apps
serviceAccount:
  # serviceAccount.create -- True | False. In case "true" new SA will be created with service.name as a SA name.
  create: false
  # serviceAccount.name -- Name of Service Account. In case serviceAccount.create is *false*, existing SA with defined name here will be used.
  name: lenses

# Lenses service
service:
  enabled: true
  type: ClusterIP
  annotations: {}

  # If you want to make it available as a node port, then add nodePort: <somePort>
  # Warning: this should not be used with servicePort:
  # Warning nodePort is deprecated and will be removed on next Lenses major version upgrade
  # nodePort:

  externalTrafficPolicy:

  ## Load balancer IP address
  ## Is not required, but allows for static address with
  ## serviceType LoadBalancer.
  ## If not supported by cloud provider, this field is ignored.
  ## Default: nil
  ##
  # loadBalancerIP: 130.211.x.x

  ## This will restrict traffic through the cloud-provider load-balancer
  ## to the specified client IPs.
  ## If not supported by cloud provider, this field is ignored.
  ## Default: nil
  ##
  # loadBalancerSourceRanges:
  #   - 0.0.0.0/0

ingress:
  ## If true, Ingress will be created
  ##
  enabled: false
  host:
  # ingressClassName:

  # Ingress annotations
  annotations: {}
    # Optionally add here the annotations related to the ingress provider, see examples below:
    # kubernetes.io/ingress.class: traefik
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: 'true'
    # nginx.ingress.kubernetes.io/rewrite-target: /

  # TLS if enabled load the tls.crt and tls.keys as a secrets and enable TLS on the ingress
  tls:
    enabled: false
    crt: |-

    key: |-

lensesHq:
  agents:
    # -- Address wherefrom agent will be listening at.
    address: ":10000"
  api:
    # -- Sets the address the HTTP servers listens at.
    address: ":8080"
    accessControlAllowOrigin: ""
    # -- SAML2 IdP configuration
    saml:
      organisationName: "my-company"
      baseUrl: ""
      entityId: ""
      # -- Example: <?xml version="1.0" ... (big blob of xml) </md:EntityDescriptor>
      metadata: |-

      # lensesHq.saml.userCreationMode --  Controls how the creation of users should be handled in relation to SSO information
      # Allowed values are: sso | manual
      userCreationMode: ""
      # lensesHq.saml.usersGroupMembershipManagementMode -- Controls how the management of a user's group membership should be handled in relation to SSO information.
      # Allowed values are: sso | manual
      usersGroupMembershipManagementMode: ""   
  
  # -- Postgres template example: "postgres://[username]:[pwd]@[host]:[port]/[database]?sslmode=require"
  postgres:
    # postgres.host -- Hostname of running postgres instance.
    host:
    # postgres.port -- Port of running postgress instance. Default is 5432.
    port:
    # postgres.username -- Username which will be used for connecting to Postgres database.
    username:
    database:
    # postgres.passwordSecret -- Definition of secret that has been precreated and has postgres database password
    passwordSecret:
      # postgres.passwordSecret.type -- Possible options: precreated | createNew
      type: "precreated"
      # Secret name
      name:
      # Secret key where password will be read from
      key:
      
      password: 
 

  logger:
    # logger.mode -- Controls the format of the logger's output.
    # Allowed values are: text | json
    mode: "text"
    # logger.level -- Controls the level of the logger
    # Allowed values are: info | debug
    level: "debug"

  tls:
    enabled: true


  # Additional env variables appended to deployment
  # Follows the format of [EnvVar spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#envvar-v1-core)
  additionalEnv:
    # - name: FOO
    #   value: bar

  # Disable livenessProbe, used while debugging
  livenessProbe:
    enabled: true

  # Pause execution of Lenses start up script to allow the user to login into the container and
  # check the running environment, used while debugging
  pauseExec:
    enabled: false

  monitoring:
    port: 9090
