image:
  repository: lensesiolocal/lenses-hq

ingress:
  host: lenses.url
lensesHq:
  agents:
    address: ""
    tls:
      enabled: false
  storage:
    postgres:
      enabled: true
      passwordSecret:
        key: lenses-db-secret
