apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-saml-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-saml
  template:
    metadata:
      labels:
        app: mock-saml
    spec:
      containers:
        - name: mock-saml
          image: boxyhq/mock-saml
          ports:
          - containerPort: 4000
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: APP_URL
            value: "http://localhost:4000"
          - name: ENTITY_ID
            value: "https://saml.example.com/entityid"
          - name: PUBLIC_KEY
            value: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiVENDQWxXZ0F3SUJBZ0lVTHlJZjZBTzFkdmZqSG9XS3BtU3NsU1FRU0Ywd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1JURUxNQWtHQTFVRUJoTUNTRkl4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpEQWdGdzB5TkRBM01ETXhNREkyTXpaYUdBOHpNREl6Ck1URXdOREV3TWpZek5sb3dSVEVMTUFrR0ExVUVCaE1DU0ZJeEV6QVJCZ05WQkFnTUNsTnZiV1V0VTNSaGRHVXgKSVRBZkJnTlZCQW9NR0VsdWRHVnlibVYwSUZkcFpHZHBkSE1nVUhSNUlFeDBaRENDQVNJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSnJwZlV4L1l6bDE4M3VLbDF3NGtEQ2VNVlk5QzRSdUovbkpPRlV4CmpKT0tBT2RIdnpFUDV1ZzZneStuTnhoQ2lvK05iZjNqU3U2aldGMlZhQUxqWTlQMjNGK1FGT3BJQjJQVDd6eGoKUXZPVTRKbm9sUVVodU1TK3ZJMWwyL3ppblkwMktQSjFDQlF4WHdMamorK3NsNE4xQ0xDaXZ5Q1MxYWpMM1l4TgpKYWZSVllDbklrUktMSE5SSm9PS2xlVC9jcXAxeTM2L1NuM0tNV2h3eFJvQnBSaVdSSzRJdzZIdFkzRHY5eTA0CjhwTW5BVndNekJzZ0dsb1ZXQS8xT1pTbWxHbmNGNXExVUkxUFJvK3pwanVXalppL240NUV1S1JoVHUyVU5tYmwKb3JHQlVKcUs0ellqVjlnc1Z4NlBlYUd1OSs1V2t4WjdIcDhBZ0dNTDk0WHRPbUVDQXdFQUFhTlRNRkV3SFFZRApWUjBPQkJZRUZHT0U3bzhtSDRIMlk1VEFVNXFnMWowUjl0V29NQjhHQTFVZEl3UVlNQmFBRkdPRTdvOG1INEgyClk1VEFVNXFnMWowUjl0V29NQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUIKQUJwTXpKRnRPcHp0UkI3RGpSV2VYM2ZlM1JGUlZVVFBJL1hoWk5TUHA3WUZKWTI1cnZLK1Y2NG9hclphRkgrZgpQcHB3SHZhd2g2bFhJZkJieW9RVzhiL3hsVUFMOFNHckFHYTVtUzJ0Q21nOWxGMEM0RWgvcXlFQ1VSY1c3NUcxCk1ibTVpbkhnN3hLTFNKNmJGbFlwOTdLNFlIOXVVRVJjRnFUK1hQSEU1aTlXbysyS25ZK01HeEREaHRMVXkySDYKTkpjSnpCcUc3bG9PUVREdXk1OEhLSTMzYlFjM0s3Znhzd2l4V0EzbUF2UFhoN0RzdE1ERWdPWW41VHljZEFHSAo4OTJnNytTTFdnVjJEOWF2L2VITUtMQzUvWVpNWWxPRUJLOEJja3JwNUZhVnRyZ0dabGpuSE9oWGplMVJrTWRjCkppOTMwTmc3LzBtazBmMnRWaDhKV2JZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg"
          - name: PRIVATE_KEY
            value: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQ2E2WDFNZjJNNWRmTjcKaXBkY09KQXduakZXUFF1RWJpZjV5VGhWTVl5VGlnRG5SNzh4RCtib09vTXZwemNZUW9xUGpXMzk0MHJ1bzFoZApsV2dDNDJQVDl0eGZrQlRxU0FkajArODhZMEx6bE9DWjZKVUZJYmpFdnJ5Tlpkdjg0cDJOTmlqeWRRZ1VNVjhDCjQ0L3ZySmVEZFFpd29yOGdrdFdveTkyTVRTV24wVldBcHlKRVNpeHpVU2FEaXBYay8zS3FkY3QrdjBwOXlqRm8KY01VYUFhVVlsa1N1Q01PaDdXTnc3L2N0T1BLVEp3RmNETXdiSUJwYUZWZ1A5VG1VcHBScDNCZWF0VkNOVDBhUApzNlk3bG8yWXY1K09STGlrWVU3dGxEWm01YUt4Z1ZDYWl1TTJJMWZZTEZjZWozbWhydmZ1VnBNV2V4NmZBSUJqCkMvZUY3VHBoQWdNQkFBRUNnZ0VBU0pLVE16ZklsZDVHczMxUmZKQTVLTFdybW1HZDJDdzlDUjIyQ045ZUlxNTMKenVJRFZXcEVQRTVSTUExdjE2c3d1NkMvd3ozczJGQm84T3F5SUF4RU04U0dLRFRaUDRwLy84b0ZYVzZKS3BENApDZEoyb2NGVERNVG9rM3VCTEg5RDNTaGUxWHR6VGZaMU11YkdBendCZlVIaVVOSGxwVTUwencrMjJtZzMrRjUwCk5CckZCN0JQU3huNXpWZGU0YzRQNFVhL3B3QitzRmNiL2REdDJuVzJpY1R0T1o2TEFTTEppd0NYenEzZ3hDeDcKNFdvZklQNlNaVWwyL0dlZTI0aFZrRlBZQ2E5bExNQ3ZpWWllNFlQRmttaVV2bmppTDI4ckhPbVdEWVhCeGlxdApOSDhNaENlQXRyQjRCZFJRa1NyZ096dDBzUVpBQmtybkhnZHlaTVVudXdLQmdRRE9CbFNhT1BSY3lUQXlUclJ5CjNhcVVDbnUzd1hVR0drVFVkM3BSTUxGRGtKWk9jajh3alZHWFdhRDV3cFVpTTBNcmVncmRTK1JlY05ZSkVMNjAKR0kxTFhkUE5VNFdKKzdIczhXTTRiN0JOZDQ2djcrUXMrUm1rYUxGaUV2c2ZGRUxZckg4YUFYSXFyMlR3L3ZuMgpFb3k5N2ZXZUJ5YTVNQ0lXbGttZzdQUlFkd0tCZ1FEQWZTMnIrMVRpeEpJYVB3cDAyVW9CK3MrVktUckN5WUYzClpndjJyOUtGbE1MMjgwS3hSNUI0L2NXa2RaNmVxcW53aGh2K1FDdkduazlZT0UyTm5nWmJhaGxudWxwUVJXRjIKcXAyZWthZ1pBNkt6RlcrQXR0OEFmUHZyUXNNVnc4bUhKa3Y3RXY5c0RVWXkxRVI2R0hWTzNkdUdCN2FjTDB1eQpkbTgyWDRzWjV3S0JnQW96ZkFycTJRYWpHNVRTR3RNNU1KSUY5dHhCWXZiN1kvOFZMMlJId2U4emdJMi8wR3NxCkJDazNVZVlzQVZCaE0yazZzTUVHV2ZkbkpPSHNCMVZKaGUxK1p0ZGExRmpoc295bDR5RFBQdTZIQmZTbUx5a2UKNkdzZ2wrL2dPcmp1T3VVWm5XMS9OdFR3UEZKR2ZiLzJhU3VhVmJnT2FKZHd6NjlJbjdxdElPZS9Bb0dBVU1zNgpCRm4yQTBqbTJrVmpxakFhTkVLR0p1R3JYRjhnREhHMHk5SjQxc0RlSkxGdWFPTFU3VFAzWlZSSlErZjJkSktWCjVWNGlBYmdwTGFwVVF3RDFRaUdDa0Z0VDFTV0tCemtOOTZURG5kdzh5bFpRK3dISEVIbGxkQllOdEhEOWdkQzkKUzZGcHZIekYza2ZpaGkwRjhCaUhML2JFMjBHdTBEV044SkNoM2prQ2dZQm9GSkJjQTQyU05sYVpwakRWQ09HbAp2Vk45a1BkTjl1THROQ2ZGRThPYXNUWTdLMFphVEJiT29La1pxQjVqeFY3dkZMWVpGc01DVXFHdUcwcWxOdUoyCncyK3FFQWdFS1VjVG42RDBmRnRrTVV1N1FhQWZIaDV6UWIyU3gyRTdudEhWczlMbEJBVEtOOVNabXUyam80UlcKMGVBbWgvUVN2TnFwdWNSRkRlcUd1dz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"
          resources:
            requests:
              memory: "1Gi"
              cpu: 1
            limits:
              memory: "2Gi"
              cpu: 1

---
apiVersion: v1
kind: Service
metadata:
  name: mock-saml-service
spec:
  selector:
    app: mock-saml
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer
  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mock-saml-ingress-1
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - pathType: ImplementationSpecific
        path: /
        backend:
          service:
            name: mock-saml-service
            port:
              number: 4000