nameOverride: ""
fullnameOverride: ""

podTemplateAnnotations: {} # Annotations here go into the PodTemplateSpec at deployment.spec.template.annotations.
labels: {}
strategy: {}
nodeSelector: {}
tolerations: {}
affinity: {}
securityContext: {}
# dnsPolicy: "None" # Optional dnsPolicy and dnsConfig to put into the Deployment's PodTemplateSpec.
# dnsConfig:
#   nameservers:
#     - 1.1.1.1
# containerSecurityContext: # Optional, plugged in into the both the deployment's main app container and the sidecar.
#   allowPrivilegeEscalation: false

# Add Prometheus annotations to the pod for Lenses metric scraping
# * The metrics path is '/metrics' and is not adjustable
# * Consumer lag metrics are exposed under 'lenses.url/metrics'. There isn't a standard way to add multiple scrape
#   targets in the annotations, so you will have to add the lag metrics target manually to your Prometheus instance.

# Resource management
# Lenses itself is bound by the JVM heap settings ('lenses.jvm.heapOpts' in the chart). The default
# heap space Lenses can use is 3GiB. If you increase the memory resource here, you will need to also
# adjust 'lenses.jvm.heapOpts'. You should allow for 1-2GiB extra space beyond the heap. So if the
# memory limit is 10Gi, set 'lenses.jvm.heapOpts' to '-Xmx8g -Xms4g'.
resources:
  requests:
  #   cpu: 1
    memory: 4Gi
  limits:
  #   cpu: 2
    memory: 5Gi

image:
  name: eu.gcr.io/k8-engine/panoptes:v6.0.0-alpha.2
  repository: 
  # -- Default to .Chart.AppVersion
  # tag:
  pullPolicy: Always
  # -- imagePullSecrets: # any image pull secrets for private registries go here
  #   - name: regcred

# rbacEnable indicates if a the cluster has rbac enabled and a cluster role
# and rolebinding should be created for the service account
rbacEnable: true

# In case rbac is enabled you can choose to enable namespace scoped roles or 
# cluster roles to be created 
namespaceScope: true

# Lense HQ container port
restPort: 8080
# Lenses HQ service port, service targets restPort
servicePort: 80
servicePortName: lenses-hq

# serviceAccount is the Service account to be used by Lenses to deploy apps
serviceAccount:
  create: false
  name: default

# Lenses service
service:
  enabled: true
  type: ClusterIP
  annotations: {}

  # If you want to make it available as a node port, then add nodePort: <somePort>
  # Warning: this should not be used with servicePort:
  # nodePort:

  externalTrafficPolicy:

  ## Load balancer IP address
  ## Is not required, but allows for static address with
  ## serviceType LoadBalancer.
  ## If not supported by cloud provider, this field is ignored.
  ## Default: nil
  ##
  # loadBalancerIP: 130.211.x.x

  ## This will restrict traffic through the cloud-provider load-balancer
  ## to the specified client IPs.
  ## If not supported by cloud provider, this field is ignored.
  ## Default: nil
  ##
  # loadBalancerSourceRanges:
  #   - 0.0.0.0/0

ingress:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: common-traefik-basic-auth@kubernetescrd
  enabled: true
  host: panoptes-test-ivan.dev-envs.k8.data-lenses.io

lensesHq:
  agents:
    address: ":10000"
  api:
    address: ":8080"
    accessControlAllowOrigin: '["https://panoptes-test-ivan.dev-envs.k8.data-lenses.io","http://panoptes-test-ivan.dev-envs.k8.data-lenses.io"]'
    saml:
      organisationName: "Lenses"
      baseUrl: "http://104.199.30.36:4000/api/saml/sso"
      entityId: "https://saml.example.com/entityid"
      # -- Example: <?xml version="1.0" ... (big blob of xml) </md:EntityDescriptor>
      metadata: |
        <md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" entityID="https://saml.example.com/entityid" validUntil="2034-07-08T14:50:44.950Z">
        <md:IDPSSODescriptor WantAuthnRequestsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
        <md:KeyDescriptor use="signing">
        <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:X509Data>
        <ds:X509Certificate>MIIDbTCCAlWgAwIBAgIULyIf6AO1dvfjHoWKpmSslSQQSF0wDQYJKoZIhvcNAQEL
        BQAwRTELMAkGA1UEBhMCSFIxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
        GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAgFw0yNDA3MDMxMDI2MzZaGA8zMDIz
        MTEwNDEwMjYzNlowRTELMAkGA1UEBhMCSFIxEzARBgNVBAgMClNvbWUtU3RhdGUx
        ITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDCCASIwDQYJKoZIhvcN
        AQEBBQADggEPADCCAQoCggEBAJrpfUx/Yzl183uKl1w4kDCeMVY9C4RuJ/nJOFUx
        jJOKAOdHvzEP5ug6gy+nNxhCio+Nbf3jSu6jWF2VaALjY9P23F+QFOpIB2PT7zxj
        QvOU4JnolQUhuMS+vI1l2/zinY02KPJ1CBQxXwLjj++sl4N1CLCivyCS1ajL3YxN
        JafRVYCnIkRKLHNRJoOKleT/cqp1y36/Sn3KMWhwxRoBpRiWRK4Iw6HtY3Dv9y04
        8pMnAVwMzBsgGloVWA/1OZSmlGncF5q1UI1PRo+zpjuWjZi/n45EuKRhTu2UNmbl
        orGBUJqK4zYjV9gsVx6PeaGu9+5WkxZ7Hp8AgGML94XtOmECAwEAAaNTMFEwHQYD
        VR0OBBYEFGOE7o8mH4H2Y5TAU5qg1j0R9tWoMB8GA1UdIwQYMBaAFGOE7o8mH4H2
        Y5TAU5qg1j0R9tWoMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB
        ABpMzJFtOpztRB7DjRWeX3fe3RFRVUTPI/XhZNSPp7YFJY25rvK+V64oarZaFH+f
        PppwHvawh6lXIfBbyoQW8b/xlUAL8SGrAGa5mS2tCmg9lF0C4Eh/qyECURcW75G1
        Mbm5inHg7xKLSJ6bFlYp97K4YH9uUERcFqT+XPHE5i9Wo+2KnY+MGxDDhtLUy2H6
        NJcJzBqG7loOQTDuy58HKI33bQc3K7fxswixWA3mAvPXh7DstMDEgOYn5TycdAGH
        892g7+SLWgV2D9av/eHMKLC5/YZMYlOEBK8Bckrp5FaVtrgGZljnHOhXje1RkMdc
        Ji930Ng7/0mk0f2tVh8JWbY=</ds:X509Certificate>
        </ds:X509Data>
        </ds:KeyInfo>
        </md:KeyDescriptor>
        <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat>
        <md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://104.199.30.36:4000/api/saml/sso"/>
        <md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://104.199.30.36:4000/api/saml/sso"/>
        </md:IDPSSODescriptor>
        </md:EntityDescriptor>
      userCreationMode: "sso"
      usersGroupMembershipManagementMode: "sso"   
  # Find more details in https://docs.lenses.io/current/installation/kubernetes/helm/#helm-storage
  ## Postgres template example: "postgres://[username]:[pwd]@[host]:[port]/[database]?sslmode=require"
  postgres:
    host: 10.52.3.55
    port: 5432
    username: postgres
    database: lenseshq
    passwordSecret:
     # type: "createNew"
     # password: OwGmPwFwez
      type: "precreated"
      name: postgres-postgresql
      key:  postgres-password
  
  logger:
    mode: "text"
    level: "debug"

  tls:
    enabled: true

  # Additional env variables appended to deployment
  # Follows the format of [EnvVar spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#envvar-v1-core)
  additionalEnv:
    # - name: FOO
    #   value: bar

  # Disable livenessProbe, used while debugging
  livenessProbe:
    enabled: false

  # Pause execution of Lenses start up script to allow the user to login into the container and
  # check the running environment, used while debugging
  pauseExec:
    enabled: false

  monitoring:
    port: 9090
