lenses:
  # Configuration necessary for agent connecting to HQ
  hq:
    agentKey:
      secret:
        # createNew | precreated | externalSecret
        type: "precreated"
        # Secret name where Lenses agent_key will be read from
        name:  name-of-precreated-agent-key-secret
        # Key from secret's data where Lenses agent_key is being stored
        key: agentkey
  provision:
    enabled: true
    version: "2"
    path: /mnt/provision-secrets
    connections:
      grpcServer:
        - name: lenses-hq
          version: 1
          tags: ['hq']
          configuration:
            server:
              value: hq-tls-test-lenses-hq.hq-agent-test.svc.cluster.local
            port:
              value: 10000
            apiKey:
              # static evnvironment value
              value: ${LENSES_HQ_AGENT_KEY}
      kafka:
      - configuration:
          additionalProperties:
            value:
              sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler
          kafkaBootstrapServers:
            value:
              - SASL_SSL://[host1]:9198,
              - SASL_SSL://[host2]:9198,
              - SASL_SSL://[host3]:9198
          metricsType:
            value: AWS
          protocol:
            value: SASL_SSL
          saslJaasConfig:
            value: software.amazon.msk.auth.iam.IAMLoginModule required awsProfileName=lenses-sa;
          saslMechanism:
            value: AWS_MSK_IAM
        name: kafka
        tags: []
        version: 1
      glueSchemaRegistry:
        - name: schema-registry
          version: 1
          tags: []
          templateName: SchemaRegistry
          configuration:
            authMode:
              reference: my-aws-connection
            glueRegistryArn:
              value: arn:aws:glue:eu-north-1:[account-id]:registry/[name]
      aws:
        - name: my-aws-connection
          version: 1
          tags: []
          configuration:
            region:
              value: eu-north-1
            authMode:
              value: "Credentials Chain"