lenses:
  # Configuration necessary for agent connecting to HQ
  hq:
    agentKey:
      secret:
        # createNew | precreated | externalSecret
        type: "precreated"
        # Secret name where Lenses agent_key will be read from
        name:  name-of-precreated-agent-key-secret
        # Key from secret's data where Lenses agent_key is being stored
        key: agentkey
  provision:
    enabled: true
    version: "2"
    path: /mnt/provision-secrets
    connections:
      lensesHq:
        - name: lenses-hq
          version: 1
          tags: ['hq']
          configuration:
            server:
              value: hq-tls-test-lenses-hq.hq-agent-test.svc.cluster.local
            port:
              value: 10000
            agentKey:
              # static evnvironment value
              value: ${LENSESHQ_AGENT_KEY}
      kafka:
        - name: kafka
          version: 1
          tags: [ "dev", "dev-2", "eu"]
          configuration:
            kafkaBootstrapServers:
              value:
                - SASL_PLAINTEXT://enjoy-v3-dev-2-kafka-bootstrap.kafka-dev.svc.cluster.local:9093
            saslJaasConfig:
              value: org.apache.kafka.common.security.scram.ScramLoginModule required username="lenses-admin-dev-2" password="GLQ8TB3WTUBDQgc6SHwKxW4GIG1nk67w";
            saslMechanism:
              value: SCRAM-SHA-512
            protocol:
              value: SASL_PLAINTEXT
            metricsType:
             value: JMX
            metricsPort:
             value: 9999
