lensesAgent:
  # Postgres connection
  storage:
    postgres:
      enabled: true
      host: postgres.url
      port: 5432
      username: postgres
      password: changeMe
      database: agent
  hq:
    agentKey:
      secret:
        type: "createNew"
        name: "agentKey"
        value: "agent_key_*"
  provision:
    path: /mnt/provision-secrets
    connections:
      lensesHq:
        - name: lenses-hq
          version: 1
          tags: ['hq']
          configuration:
            server:
              value: hq-tls-test-lenses-hq.hq-agent-test.svc.cluster.local
            port:
              value: 10000
            agentKey:
              value: ${LENSESHQ_AGENT_KEY}
      kafka:
       - name: kafka
         version: 1
         tags: [ "dev", "dev-2", "eu"]
         configuration:
           kafkaBootstrapServers:
             value:
               - SASL_SSL://<namespace>.servicebus.windows.net:9093
           #saslJaasConfig:
           #  value: ${SASL_JAAS_CONFIG}
           saslMechanism:
               value: PLAIN
           protocol:
             value: SASL_SSL
           saslJaasConfig:
              value: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://<enter_the_rest_of_the_connectrion_string_here>";
