lensesAgent:
  # Postgres connection
  storage:
    postgres:
      enabled: true
      host: postgres.url
      port: 5432
      username: postgres
      password: changeMe
      database: agent
  hq:
    agentKey:
      secret:
        type: "createNew"
        name: "agentKey"
        value: "agent_key_*"
  provision:
    path: /mnt/provision-secrets
    connections:
      lensesHq:
        - name: lenses-hq
          version: 1
          tags: ['hq']
          configuration:
            server:
              value: hq-tls-test-lenses-hq.hq-agent-test.svc.cluster.local
            port:
              value: 10000
            agentKey:
              value: ${LENSESHQ_AGENT_KEY}
      kafka:
      - name: kafka
        version: 1
        tags: ["optional-tag"]
        configuration:
          kafkaBootstrapServers:
            value:
            - SASL_SSL://your.kafka.broker.0:9098
            - SASL_SSL://your.kafka.broker.1:9098
          protocol:
            value: SASL_SSL
          saslMechanism:
            value: AWS_MSK_IAM
          saslJaasConfig:
            value: software.amazon.msk.auth.iam.IAMLoginModule required;
          additionalProperties:
            value:
              sasl.client.callback.handler.class: "software.amazon.msk.auth.iam.IAMClientCallbackHandler"
