lensesAgent:
  # Postgres connection
  storage:
    postgres:
      enabled: true
      host: postgres.url
      port: 5432
      username: postgres
      password: changeMe
      database: agent
  hq:
    agentKey:
      secret:
        type: "createNew"
        name: "agentKey"
        value: "agent_key_*"
  provision:
    path: /mnt/provision-secrets
    connections:
      lensesHq:
        - name: lenses-hq
          version: 1
          tags: ['hq']
          configuration:
            server:
              value: hq-tls-test-lenses-hq.hq-agent-test.svc.cluster.local
            port:
              value: 10000
            agentKey:
              value: ${LENSESHQ_AGENT_KEY}
      kafka:
      - name: Kafka
        version: 1
        tags: [my-tag]
        configuration:
          kafkaBootstrapServers:
            value:
              - SASL_SSL://your.kafka.broker.0:9092
              - SASL_SSL://your.kafka.broker.1:9092
          protocol:
            value: SASL_SSL
          sslTruststore:
            file: /path/to/truststore.jks
          sslTruststorePassword:
            value: truststorePassword
          # Use value below in case additionalEnv is used
          # value: ${LENSES_AGENT_TRUSTSTORE_PWD}
          saslMechanism:
            value: PLAIN
          saslJaasConfig:
            value: |
              org.apache.kafka.common.security.plain.PlainLoginModule required
              username="your-username"
              password="your-password";
additionalVolumeMounts:
  - name: agent-truststore
    mountPath: "/mnt/provision-secrets/agent"

additionalVolumes:
  - name: agent-truststore
    secret:
      secretName: agent-truststore

# TIP:
# Use following code snippet in order to read keypassword - keystorepassword - truststorepassword from secret  additionalEnv:
  # additionalEnv:
  #   - name: LENSES_AGENT_TRUSTSTORE_PWD
  #     valueFrom:
  #       secretKeyRef:
  #         name: [SECRET_NAME]
  #         key: [SECRET_KEY]
