### https://docs.lenses.io/6.0/installation/getting-started/helm/ ###

nameOverride: ""
fullnameOverride: ""

image:
  repository:
  # Default to .Chart.AppVersion
  tag: panoptes
  pullPolicy: Always
  imagePullSecrets: # any image pull secrets for private registries go here
    - name: gcr-key

annotations: {}
podTemplateAnnotations: {} # Annotations here go into the PodTemplateSpec at deployment.spec.template.annotations.
labels: {}
strategy: {}
nodeSelector: {}
tolerations: {}
affinity: {}
securityContext: {}

monitoring:
  enabled: true
  port: 9102

resources:
  requests:
  #   cpu: 1
    memory: 3Gi
  limits:
  #   cpu: 2
    memory: 5Gi


rbacEnable: true

# Lenses container port
restPort: 3030
servicePortName: lenses

serviceAccount:
  create: true
  name: lenses


persistence:
  log:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    storageClass: ebs-csi-sc

additionalVolumeMounts:
  - name: grpc-truststore
    mountPath: "/mnt/provision-secrets/grpc"

additionalVolumes:
  - name: grpc-truststore
    secret:
      secretName: hq-agent-test-authority


# Lenses service
service:
  enabled: true
  annotations: {}

containerSecurityContext:
  readOnlyRootFilesystem: false

lensesAgent:
  # Configuration necessary for agent connecting to HQ
  hq:
    agentKey:
      secret:
        # createNew | precreated | externalSecret
        type: "createNew"
        name: "agentKey"
        value: "agent_key_kU919kP32b0w7EiV_6d9Lv4Tm3dmvPH4bjyOz4vgqukSLTZ3o"

  provision:
    enabled: true
    version: "2"
    path: /mnt/provision-secrets
    connections:
      lensesHq:
        - name: lenses-hq
          version: 1
          tags: ['hq']
          configuration:
            server:
              value: hq-tls-test-lenses-hq.hq-agent-test.svc.cluster.local
            port:
              value: 10000
            agentKey:
              value: ${LENSESHQ_AGENT_KEY}
            sslEnabled:
              value: true
            sslTruststore:
              file: "/mnt/provision-secrets/grpc/truststore.jks"
            sslTruststorePassword:
              value: ${LENSES_HQ_AGENT_TRUSTSTORE_PWD}
      kafka:
        - name: kafka
          version: 1
          tags: [ "dev", "dev-2", "eu"]
          configuration:
            kafkaBootstrapServers:
              value:
                - SASL_PLAINTEXT://enjoy-v3-dev-2-kafka-bootstrap.kafka-dev.svc.cluster.local:9093
            saslJaasConfig:
              value: org.apache.kafka.common.security.scram.ScramLoginModule required username="lenses-admin-dev-2" password="GLQ8TB3WTUBDQgc6SHwKxW4GIG1nk67w";
            saslMechanism:
              value: SCRAM-SHA-512
            protocol:
              value: SASL_PLAINTEXT
            metricsType:
             value: JMX
            metricsPort:
             value: 9999


  sql:
    # processorImage: lensesioextra/sql-processor
    # processorImageTag: 5.5
    mode: IN_PROC
    heap: 1024M
    minHeap: 128M
    memLimit: 1152M
    memRequest: 128M
    livenessInitialDelay: 60 seconds

  additionalEnv:
    - name: LENSES_HQ_AGENT_TRUSTSTORE_PWD
      valueFrom:
        secretKeyRef:
          name: hq-agent-test-authority
          key: truststore.jks.password
